server:
  port: 8000

spring:
  data:
    rest:
      basePath: /api
      defaultMediaType: application/json
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    name: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE