server:
  port: 8000
  tomcat:
    basedir: /spring-boot-tomcat
spring:
  data:
    rest:
      basePath: /api
      defaultMediaType: application/json
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE