server:
  port: 8000

spring:
  application:
    name: account-service
  data:
    rest:
      basePath: /api
      defaultMediaType: application/json
  datasource:
    url:
    name:
    password:
    driver-class-name:

cloud:
  config:
    uri: http://192.168.1.255:8888
    fail-fast: true